// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pagesize/pagesize.proto

package pagesize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageSizeValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultPageSize int32 `protobuf:"varint,1,opt,name=default_page_size,json=defaultPageSize,proto3" json:"default_page_size,omitempty"`
	MaxPageSize     int32 `protobuf:"varint,2,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
}

func (x *PageSizeValues) Reset() {
	*x = PageSizeValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pagesize_pagesize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageSizeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSizeValues) ProtoMessage() {}

func (x *PageSizeValues) ProtoReflect() protoreflect.Message {
	mi := &file_pagesize_pagesize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSizeValues.ProtoReflect.Descriptor instead.
func (*PageSizeValues) Descriptor() ([]byte, []int) {
	return file_pagesize_pagesize_proto_rawDescGZIP(), []int{0}
}

func (x *PageSizeValues) GetDefaultPageSize() int32 {
	if x != nil {
		return x.DefaultPageSize
	}
	return 0
}

func (x *PageSizeValues) GetMaxPageSize() int32 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

var file_pagesize_pagesize_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PageSizeValues)(nil),
		Field:         1159,
		Name:          "pagesize.field",
		Tag:           "bytes,1159,opt,name=field",
		Filename:      "pagesize/pagesize.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional pagesize.PageSizeValues field = 1159;
	E_Field = &file_pagesize_pagesize_proto_extTypes[0]
)

var File_pagesize_pagesize_proto protoreflect.FileDescriptor

var file_pagesize_pagesize_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x3a, 0x51, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x87, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a,
	0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x63, 0x6d, 0x61, 0x67, 0x75, 0x69,
	0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f,
	0x2d, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pagesize_pagesize_proto_rawDescOnce sync.Once
	file_pagesize_pagesize_proto_rawDescData = file_pagesize_pagesize_proto_rawDesc
)

func file_pagesize_pagesize_proto_rawDescGZIP() []byte {
	file_pagesize_pagesize_proto_rawDescOnce.Do(func() {
		file_pagesize_pagesize_proto_rawDescData = protoimpl.X.CompressGZIP(file_pagesize_pagesize_proto_rawDescData)
	})
	return file_pagesize_pagesize_proto_rawDescData
}

var file_pagesize_pagesize_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pagesize_pagesize_proto_goTypes = []interface{}{
	(*PageSizeValues)(nil),            // 0: pagesize.PageSizeValues
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_pagesize_pagesize_proto_depIdxs = []int32{
	1, // 0: pagesize.field:extendee -> google.protobuf.FieldOptions
	0, // 1: pagesize.field:type_name -> pagesize.PageSizeValues
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pagesize_pagesize_proto_init() }
func file_pagesize_pagesize_proto_init() {
	if File_pagesize_pagesize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pagesize_pagesize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageSizeValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pagesize_pagesize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pagesize_pagesize_proto_goTypes,
		DependencyIndexes: file_pagesize_pagesize_proto_depIdxs,
		MessageInfos:      file_pagesize_pagesize_proto_msgTypes,
		ExtensionInfos:    file_pagesize_pagesize_proto_extTypes,
	}.Build()
	File_pagesize_pagesize_proto = out.File
	file_pagesize_pagesize_proto_rawDesc = nil
	file_pagesize_pagesize_proto_goTypes = nil
	file_pagesize_pagesize_proto_depIdxs = nil
}
